apiVersion: v1
kind: Config


clusters:
-  cluster:
      server: https://172.28.12.11:6443
      certificate-authority: /root/.kube/ca.crt
   name: kubernetes


contexts:
-  context:
      cluster: kubernetes-admin@kubernetes
      user: ravi_cept






users:
-  name: ravi_cept
   user:
     client-key: /root/.kube/client.key
     client-certificate: /root/.kube/client.crt



